LineaBase/urls.py
from django.urls import path, re_path
from .views import Subir_Linea, Drive_manage, Crear_Encuesta, Nueva_Pregunta, Excel_to_bd, Geocoordenadas, Giras
from .views import Graficos, Preguntas, Diagnostico

app_name = 'lineabase'
urlpatterns = [
    path('subir/', Subir_Linea.as_view(), name="subir"),
    path('drive/',Drive_manage.as_view(), name='drive'),
    path('crear_1/',Crear_Encuesta.as_view(),name='crear'),
    path('nueva_pregutna/', Nueva_Pregunta.as_view(),name='nueva_pregunta'),
    path('preguntas/', Preguntas.as_view(),name='preguntas'),
    path('graficos/', Graficos.as_view(),name='graficos'),
    path('excel_to_bd/',Excel_to_bd.as_view(),name = "excel"),
    path('coordenadas/',Geocoordenadas.as_view(),name = "coordenadas"),
    path('giras/',Giras.as_view(),name = "giras"),
    path('capacitaciones/',Diagnostico.as_view(),name = "capacitaciones"),


]

Monitore/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Paso, Paso1
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Paso.as_view(), name ='inicio'),
    path('accounts/profile/', Paso1.as_view()),
    path('users/', include('users.urls', namespace='users')),
    path('lineabase/', include('LineaBase.urls', namespace='lineabase')),
]

users/urls.py
from django.urls import path

from .views import  LogoutView, UserLoginView, Paso


app_name = 'users'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path("profile/", Paso.as_view()),
    #path("profile/librodiario/", Cargar()),


]

templates/Lineas_Base/Buscar_Linea_Base.html
{% extends 'core/base.html' %}

{% block content %}

        <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2> Mostrar Linea Base</h2>
                    </div>

                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Single Page Start -->
        <div class="single">
            <div class="container">
                <div class="section-header text-center">
                    <h2>Mostrar Linea Base</h2>
                </div>
            </div>
                <center>
                <div class="row">
                    <div class="col-12">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ formulario.as_p }}
                    <div>
                    <button class="btn" type="submit" id="sendMessageButton">Buscar</button>
                    </div>
                </form>
                    </div>
                    </div>
                    </center>
            </div>
        </div>
        <!-- Single Page End -->
{% endblock %}

templates/Lineas_Base/Crear_Linea_Base.html
{% extends 'core/base.html' %}

{% block content %}

        <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Nueva Linea Base</h2>
                    </div>

                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Single Page Start -->
        <div class="single">
            <div class="container">
                <div class="section-header text-center">
                    <h2>Crear Linea Base</h2>
                </div>
            </div>
                <center>
                <div class="row">
                    <div class="col-12">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ formulario.as_p }}
                    <div>
                    <button class="btn" type="submit" id="sendMessageButton">Cargar</button>
                    </div>
                </form>
                    </div>
                    </div>
                    </center>
            </div>
        </div>
        <!-- Single Page End -->
{% endblock %}

templates/Lineas_Base/Index.html
{% extends 'core/base.html' %}

{% block content %}
    <!-- Page Header Start -->

        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>ARA DATA MANAGER</h2>
                    </div>
                    <!--
                    <div class="col-12">
                        <a href="{% url 'lineabase:nueva_pregunta' %}" type="submit" >Crear</a>
                        <a href="{% url 'lineabase:subir' %}">Subir</a>
                        <a href="{% url 'lineabase:graficos' %}">Graficos</a>
                        <a href="{% url 'lineabase:excel' %}">Excel</a>
                        <a href="{% url 'lineabase:coordenadas' %}">Coordenadas</a>
                    </div>-->
                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Single Page Start -->

        <div class="single">

            <div class="container">
              <!--  <div class="section-header text-center">
                    <h2>ARA Data Manager</h2>
                </div>-->
                <div class="row">
                    <div class="col-12">

                        <h1>¿Qué es el modulo Data Manager?</h1>

                        <p>
                            Este módulo del sistema permite el levantamiento de encuesta, haciendo uso de dispositivos móviles android. Para la correcta utilización de este sistema es necesario  proveer una encuesta en formato XML, además se deben sincronizar los dispositivos para la recolección de la información; las instrucciones para dicho proceso aparecen a continuación.
                        </p>

                         <h1>¿Cómo funciona?</h1>
                        <p>
                            Los pasos para subir una encuesta en el sistema son:

                        </p>
                        <ul class="ul-group">
                            <li>1. Crear la encuesta.</li>
                            <li>2. Exportar la encuesta en formato XML.</li>
                            <li>3. Subir la Encuesta en formato XML.</li>
                            <li>4. Sincronizar los dispositivos de recolección de datos.</li>
                            <li>5. Bajar la encuesta en los dispositivos móviles.</li>
                            <li>6. Levantar las encuestas.</li>
                            <li>7. Subir las  respuestas al servidor.</li>

                        </ul>
                        <h3>1. Crear encuesta</h3>
                        <p>
                            Para la creación de la encuesta se puede utilizar algún sistema de creación de encuestas,  a continuación utilizaremos Koobotool, sin embargo, es pertinente aclarar que no es el único servicio.

                        </p>
                        <p>
                            Para utilizar Koobotool, es necesario la creación de una cuenta Koobo, para eso puede ver el siguiente vídeo:
                        </p>
                        <center>
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/p5ACa4BMTh0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </center>
                        <p>
                            Luego de crear su cuenta, debe ingresar  con sus credenciales, luego se debe crear la encuesta.   Para crear una nueva encuesta vea el siguiente vídeo:
                        </p>
                        <center>
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/LFvCVwj9z8k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </center>
                        <h3>2. Exportar encuesta en XML </h3>
                        <p>
                            Al terminar la encuesta se debe guardar todos los cambios, luego se debe exportar esta encuesta, para esto en su menú principal, donde aparecen todas las encuestas creadas, debe dar click en los tres puntos que aparecen al final de cada fila, luego seleccionar descargar XML.
                        </p>

                        <

                    </div>
                </div>
            </div>
        </div>
        <center>
        <img src="/static/img/1.png" alt="Image" width="207" height="344" />
         </center>
    <div class="single">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                     <div>
                         Esto le permitirá descargar un archivo tipo XML, el cual debe subir en el siguiente paso.
                     </div>
                    <h3>3. Subir la encuesta en formato XML. </h3>
                     <div>
                         Luego de tener el archivo XML, se ingresa a la pestaña de subir encuesta, dónde deberá seleccionar el archivo descargado en el paso anterior, además completar los campos solicitados.

                            Luego de esto,  la encuesta aparecerá lista para ser descargada en los dispositivos móviles

                     </div>
                     <h3>4. Sincronizar los dispositivos de recolección de datos</h3>

                    </div>
                </div>
            </div>
    </div>
    <center>
        <img src="/static/img/Imagen1.jpg" alt="Image" width="500" height="344" />
     </center>
    <div class="single">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                    Luego se debe seguir los pasos mostrados en las siguientes imágenes, para configurar el dispositivo.
                    </div>
                </div>
            </div>
    </div>
    <center>
        <img src="/static/img/Imagen2.png" alt="Image" width="225" height="375" />
     </center>
    <center>
        <img src="/static/img/Imagen3.png" alt="Image" width="225" height="375" />
     </center>
    <center>
        <img src="/static/img/Imagen4.png" alt="Image" width="225" height="375" />
     </center>
    <div class="single">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                    En este punto se debe ingresar las credenciales provistas  por la Coordinación de Proyectos.
                    </div>
                <h3>Bajar la encuesta en los dispositivos móviles.</h3>
                </div>
            </div>
    </div>


    <!-- Single Page End -->
{% endblock %}

templates/Lineas_Base/Nueva_Pregunta.html
{% extends 'core/base.html' %}

{% block content %}

        <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Nueva Pregunta</h2>
                    </div>

                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Single Page Start -->
        <div class="single">
            <div class="container">
                <div class="section-header text-center">
                    <h2>Crear Pregunta</h2>
                </div>
            </div>
                <center>
                <div class="row">
                    <div class="col-12">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                     <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                        Tipo de Pregunta
                     </label>
                    <select name="Tipo_q" id="Tipo_q">
                        <option value="text">Texto</option>
                        <option value="num">Numérico</option>
                        <option value="multi">Selección Múltiple</option>
                        <option value="uni">Selección Única </option>
                        <option value="foto"> Foto </option>
                        <option value="Ubi"> Ubicación </option>
                    </select></br>
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                        Enunciado
                    </label>
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Enunciado" id="Enunciado"  required placeholder="Enunciado">
                    </br>
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                        Opciones
                    </label>
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Opciones" id="Opciones"  required placeholder="Opciones">

                    <div>
                    <button class="btn" type="submit" id="sendMessageButton">Guardar</button>
                    </div>
                </form>
                    </div>
                    </div>
                    </center>
            </div>
        </div>
        <!-- Single Page End -->
{% endblock %}

templates/Lineas_Base/graficos.html
{% extends 'core/base.html' %}

{% block content %}

        <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Encuesta {{ Encuesta }}</h2>
                    </div>

                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Single Page Start -->
        <div class="single">
            <div class="container">
                <div class="section-header text-center">
                    <h2>Pregunta {{ Pregunta }}</h2>
                </div>
            </div>
                <center>
                <head>
                    <title>FC-python wrapper</title>

                <!-- If you are using downloaded FusionCharts libraries, uncomment the below code   -->
                <!--

                    {% load static %}
                    <script type="text/javascript" src="{% static "fusioncharts/fusioncharts.js" %}"></script>
                    <script type="text/javascript" src="{% static "fusioncharts/themes/fusioncharts.theme.fusion.js" %}"></script>

                -->

                   <script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
                   <script type="text/javascript" src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js "></script>

                </head>
                <body style="font-family:'Helvetica Neue', Arial; font-size: 16px;">
                    <h3>{{ chartTitle|safe }}</h3>
                    <div id="chart-1">{{ output|safe }}</div>
                    <div id="chart-2">{{ output_2|safe }}</div>
                    <br/>

                </body>
                    </center>
            </div>
        </div>
        <!-- Single Page End -->
{% endblock %}

templates/Lineas_Base/graficos_form.html
{% extends 'core/base.html' %}

{% block content %}

        <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Mostrar Gráfico</h2>
                    </div>

                </div>
            </div>
        </div>
        <!-- Page Header End -->


        <!-- Single Page Start -->
       <!-- <div class="single">
            <div class="container">
                <center>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div>
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                                Encuesta
                            </label>
                        </div>
                        <div>
                            <select class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Encuesta" id="Encuesta"  required placeholder="Encuesta">

                                <option value="1">¿Sabe quien es el financiador del proyecto?</option>

                            </select>
                        </div>
                        <div>
                            <button class="btn" type="submit" id="sendMessageButton">Seleccionar</button></div>
                    </form>

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div>
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                                Pregunta
                            </label>
                        </div>
                        <div>
                            <select class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Pregunta" id="Pregunta"  required placeholder="Pregunta">

                            </select>
                        </div>
                        <div>
                            <button class="btn" type="submit" id="sendMessageButton">Gráficar</button>
                        </div>
                    </form>
                </center>
            </div>
        </div>-->
    <center>
        <div class="row">
            <div class="col-12">
                <form action="/lineabase/preguntas/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Encuesta</label>
                          <br/>
                        <select class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Encuesta" id="Encuesta"  required placeholder="Encuesta" href="http://127.0.0.1:8000/lineabase/coordenadas/">
                            {{ option|safe }}
                        </select>
                    </div>

                </form>
            </div>
        </div>
        <div class="row">
                <div class="col-12">
                    <form action="/lineabase/graficos/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Pregunta</label>
                              <br/>
                            <select class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Pregunta" id="Pregunta"  required placeholder="Pregunta" onchange="this.form.submit()">
                            {{ option1|safe }}
                        </select>
                        </div>

                    </form>

                </div>
            </div>

    </center>


        <!-- Single Page End -->
{% endblock %}