LineaBase/urls.py
from django.urls import path, re_path
from .views import Subir_Linea, Drive_manage, Crear_Encuesta, Nueva_Pregunta, Excel_to_bd, Geocoordenadas, Giras
from .views import Graficos, Preguntas, Diagnostico

app_name = 'lineabase'
urlpatterns = [
    path('subir/', Subir_Linea.as_view(), name="subir"),
    path('drive/',Drive_manage.as_view(), name='drive'),
    path('crear_1/',Crear_Encuesta.as_view(),name='crear'),
    path('nueva_pregutna/', Nueva_Pregunta.as_view(),name='nueva_pregunta'),
    path('preguntas/', Preguntas.as_view(),name='preguntas'),
    path('graficos/', Graficos.as_view(),name='graficos'),
    path('excel_to_bd/',Excel_to_bd.as_view(),name = "excel"),
    path('coordenadas/',Geocoordenadas.as_view(),name = "coordenadas"),
    path('giras/',Giras.as_view(),name = "giras"),
    path('capacitaciones/',Diagnostico.as_view(),name = "capacitaciones"),


]

Monitore/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Paso, Paso1
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Paso.as_view(), name ='inicio'),
    path('accounts/profile/', Paso1.as_view()),
    path('users/', include('users.urls', namespace='users')),
    path('lineabase/', include('LineaBase.urls', namespace='lineabase')),
]

users/urls.py
from django.urls import path

from .views import  LogoutView, UserLoginView, Paso


app_name = 'users'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path("profile/", Paso.as_view()),
    #path("profile/librodiario/", Cargar()),


]

templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
        <title>Sistema de Líneas Base</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free Website Template" name="keywords">
        <meta content="Free Website Template" name="description">

        <!-- Favicon -->
        <link href={%  static "img/favicon.ico" %} rel="icon">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="lib/animate/animate.min.css" rel="stylesheet">
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href={% static "css/style.css" %} rel="stylesheet">
</head>
<body>
     <!-- Top Bar Start -->
        <div class="top-bar d-none d-md-block">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="top-bar-left">
                            <div class="text">
                                <h2>9:00-17:00</h2>
                                <p>Lun - Vie</p>
                            </div>
                            <div class="text">
                                <h2>2237-3318</h2>
                                <p>Teléfono</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="top-bar-right">
                            <div class="social">
                                <a href="https://twitter.com/caritashonduras?s=20&t=-amkvJXOC4UENavfEfdhcw"><i class="fab fa-twitter"></i></a>
                                <a href="https://www.facebook.com/caritashonduras"><i class="fab fa-facebook-f"></i></a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top Bar End -->
         <!-- Nav Bar Start -->
        <div class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container-fluid">
                <a href="" class="navbar-brand">SAPTVPC<span>I</span></a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto">
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle active" data-toggle="dropdown">Crear </a>
                            <div class="dropdown-menu">
                              <!--  <a href="{% url 'lineabase:crear' %}" class="dropdown-item">Crear</a>-->
                                <a href="{% url 'lineabase:subir' %}" class="dropdown-item">Subir</a>
                                <a href="{% url 'lineabase:coordenadas' %}" class="dropdown-item">Mostrar</a>
                                <a href="{% url 'lineabase:giras' %}" class="dropdown-item">Giras</a>
                                <a href="{% url 'lineabase:capacitaciones' %}" class="dropdown-item">Capacitaciones</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Nav Bar End -->

        {% block content %}
            <!-- Add content here -->
        {% endblock %}
        <!-- Footer Start -->
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="footer-contact">
                                    <h2>Salon Address</h2>
                                    <p><i class="fa fa-map-marker-alt"></i>Calle El Telegrafo, Tegucigalpa</p>
                                    <p><i class="fa fa-phone-alt"></i>2237-3318</p>
                                    <p><i class="fa fa-envelope"></i>caritas_de_honduras@caritas.hn</p>
                                    <div class="footer-social">
                                        <a href="https://twitter.com/caritashonduras?s=20&t=-amkvJXOC4UENavfEfdhcw"><i class="fab fa-twitter"></i></a>
                                        <a href="https://www.facebook.com/caritashonduras"><i class="fab fa-facebook-f"></i></a>
                                        <a href="https://www.youtube.com/channel/UCK0717W-9up0U2MVYEmyglQ"><i class="fab fa-youtube"></i></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="footer-link">
                                    <h2>Quick Links</h2>
                                    <a href="">Terms of use</a>
                                    <a href="">Privacy policy</a>
                                    <a href="">Cookies</a>
                                    <a href="">Help</a>
                                    <a href="">FQAs</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="container copyright">
                <div class="row">
                    <div class="col-md-6">
                        <p>&copy; <a href="#">Your Site Name</a>, All Right Reserved.</p>
                    </div>
                    <div class="col-md-6">
                        <p>Designed By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/isotope/isotope.pkgd.min.js"></script>
        <script src="lib/lightbox/js/lightbox.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
        <script src="https://maps.google.com/maps/api/js?sensor=true"></script>


        <!-- Contact Javascript File -->
        <script src="mail/jqBootstrapValidation.min.js"></script>
        <script src="mail/contact.js"></script>

        <!-- Template Javascript -->
        <script src="js/main.js"></script>
    </body>




</html>